### ISSUE TITLE
Update at node-red

### ISSUE THREAD

**Issue by Moosbueffel** [mabunixda/node-red-contrib-fronius-solar#11]
Please can you update your version on node-red.org. I don't know, how to install from git :-(

**Comment by mabunixda** [comment]
@Moosbueffel the actual version should be available already? next one coming up ...

**Comment by Moosbueffel** [comment]
?? there is always version 0.1.3
https://flows.nodered.org/node/node-red-contrib-fronius-solar

**Comment by mabunixda** [comment]
yeah this must be done manually now - I missed that info. it is up-to-date now. 
you find the up-to-date version on https://www.npmjs.com/package/node-red-contrib-fronius-solar. this Is done automatically.  That is also the source for installation, but i gonna review how this can be automated
