### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by langepil** [mabunixda/node-red-contrib-fronius-solar#2]
Hello,

the installation in NodeRed fails as well as the installation via the terminal.

<img width="701" alt="Bildschirmfoto 2019-11-06 um 04 24 21" src="https://user-images.githubusercontent.com/50093063/68265793-60848200-004d-11ea-95fe-c607d19a9914.png">
[2019-11-06T03_22_00_731Z-debug.log](https://github.com/mabunixda/node-red-contrib-fronius-solar/files/3812400/2019-11-06T03_22_00_731Z-debug.log)

**Comment by AloisKlingler** [comment]
you need to install git: "sudo apt-get install git"

**Comment by mabunixda** [comment]
Thanks @AloisKlingler
