### ISSUE TITLE
Turn off console.logs or add a config parameter for debugging

### ISSUE THREAD

**Issue by coolchip** [mabunixda/node-red-contrib-fronius-solar#23]
Thank you very, very much for that node. This helps me a lot and works excelent.
But it would be very great if you can remove those console.logs. All those logs went into my node-red journal file. Sometimes I look at it to find errors but at the moment I only see the logs from your node. ;-)
It also would be possible to add an debug switch to the configuration. I also can send you a pull request, of you want to.

**Comment by mabunixda** [comment]
I totally missed those console outputs :( 

new version 1.0.3 without the log outputs is online

**Comment by coolchip** [comment]
That was fast! Thank you very, very much.
