### ISSUE TITLE
trying to configure and use, but failing

### ISSUE THREAD

**Issue by pacraf** [mabunixda/node-red-contrib-fronius-solar#4]
thank you for sharing node. 
unfortunatelly I can not make it work for me. 
I configured node (IP, ID). 
but what should I inject to get answer? could not find any example... 
could you guide a bit on this matter?
below is my test flow (I am not sure if device ID should be kept secret - so last 4 digits are xxxxed)

![nodes](https://user-images.githubusercontent.com/8949690/78982500-8ba25e80-7b22-11ea-9a2a-8f3f8b34921f.png)

Here below is how node is configured:

![node_config](https://user-images.githubusercontent.com/8949690/78982483-8513e700-7b22-11ea-8de9-2719764004ae.png)

and here how I tried to inject query... most probavly failed here... 
![node_configa](https://user-images.githubusercontent.com/8949690/78982494-89400480-7b22-11ea-9430-409e821a2320.png)

my inverter answers some browser api request, like here, so seems to be OK
for example pointing browser here http://192.168.55.127/solar_api/v1/GetInverterRealtimeData.cgi
gives answer:

{
Body: {
Data: { }
},
Head: {
RequestArguments: {
DeviceClass: "Inverter",
Scope: ""
},
Status: {
Code: 6,
Reason: "CGI-Args: Invalid parameter '' for attribute 'Scope' (use 'System' or 'Device')",
UserMessage: ""
},
Timestamp: "2020-04-10T11:44:44+02:00"
}
}

kind regards, rafael.

**Comment by mabunixda** [comment]
Hi, 
where did you get your device id from?
I am just using 1 as device id. The device id is indexing the converters from my point of view

**Comment by pacraf** [comment]
According googling results it is unique number you can see for example when turning it into ap mode. I followed this guide to get it:
https://youtu.be/vILngSsrxCI

**Comment by mabunixda** [comment]
Can you give it a try with 1 as ID ?

**Comment by pacraf** [comment]
Yes, sure. But other part of setup look ok for you? 
What I would like really to read is current generating power, and daily production.
What payload should I use to have proper response?

**Comment by pacraf** [comment]
just tried with 1 as ID 
deployed, and stuck on the same - no response in debug monitor.
But also I dont know what to inject to input to have any response?

I tried few injection query , but always no answer in debug monitor, and red (error?) note [Object object]
look below on attached picture.
![nodes_2](https://user-images.githubusercontent.com/8949690/79423666-4d43ee00-7fbf-11ea-8033-c0cdb13e5232.png)

**Comment by mabunixda** [comment]
Can you post a screenshot of your inverter node? 
I assume you are on the wrong API version - go on 0 which should be default

**Comment by mabunixda** [comment]
My configuration looks like following: ![image](https://user-images.githubusercontent.com/1193145/79429709-305fe880-7fc8-11ea-9b4c-afacfeac8460.png)

a timestamp is injected - could be also empty string - is afterwards transformed to a valid influxdb insert object and inserted into an influx table

**Comment by pacraf** [comment]
You were right - choosen was API version to 1.  Now it responds, and I can process data further.
![output_fronius_json](https://user-images.githubusercontent.com/8949690/79451040-29e06980-7fe6-11ea-8151-542bd17503d1.png)
THANK YOU onece again for sharing the node and assistance.

I think it is time to close the issue. 

or maybe before , you could share how do you utilise your data? it goes to influx for  storage and later visualisation? on what platform? 



In my case it will be added very soon to "kindle weather display" , which I recomend to every enthusiast of node red , smart home etc.

**Comment by mabunixda** [comment]
The data is stored within influx and visualized in grafana like all house related data. 
I wanted to get some vis into my smart-home app but was not very motivated to do this ;-)

I gonna add an example flow within the repo ... and update the readme
